---
  - name: Shell Examples
    hosts: all
    become: yes
    become_user: vt_admin
    tasks:
    - name: Check Date with Shell command
      shell:
         "date"
      register: datecmd
      tags: datecmd
    - debug: msg="{{datecmd.stdout}}"
