---
  - name: IP tables Examples
    hosts: all
    become: yes
    ansible_become_user: vt_admin
    ansible_become_method: sudo
    tasks:
    - name: Allow port 80 http
      iptables_raw:
         name: allow_tcp_80
         rules: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
