---
  - name: Shell Examples
    hosts: all
    tasks:
    - name: Check Date with Shell command
      become: yes
      #become_user: vt_admin
      shell:
         "date"
      register: datecmd
      tags: datecmd
    - debug: msg="{{datecmd.stdout}}"
