---
- name: IP tables Examples
  hosts: all
  become: yes
  become_user: root
  tasks:
  #check user id before excute command
  - name: check user id
    shell:
      "id"
    register: id_var
    tags: idcmd
  - debug: msg="{{id_var.stdout}}"
  #Allow rule port 80 http
  - name: Allow port 80 http
    iptables_raw:
      name: allow_tcp_80
      rules: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
  #check result iptables
  - name: check iptables
    shell:
      "iptables -L"
    register: iptbl_var
    tags: iptbl_var
  - debug: msg="{{iptbl_var.stdout}}"
