---
  - name: IP tables Examples
    hosts: all
    tasks:
    - name: Allow port 80 http      
      iptables_raw:
         name: allow_tcp_80
         rules: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
